# Generated by Django 3.0 on 2020-08-17 07:54

from django.db import migrations, models
import django.utils.timezone
import qx_base.qx_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('star_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Post',
            },
            bases=(models.Model, qx_base.qx_core.models.ModelCountMixin),
        ),
    ]
