# Generated by Django 3.0.8 on 2020-08-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_baby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True, null=True, verbose_name='对象Id'),
        ),
    ]
