# Generated by Django 3.0.8 on 2020-08-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200806_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='user_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='用户Id'),
        ),
    ]
