# Generated by Django 3.1.7 on 2021-04-08 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201113_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgroup',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间'),
        ),
    ]
